(function(root){
  'use strict';const D=root.DC,E=D.safeText;
  const TAGS={water:'水系',food:'食物',geo:'地质',study:'学习',tech:'科技',daily:'日常',electric:'电系'};
  const TYPES={shot:'直射',spread:'散射',burst:'连发',beam:'贯穿激光',homing:'追踪',lob:'抛物爆弹',boomerang:'往返回旋',melee:'扇形近战',wave:'穿透冲击波',chain:'连锁电弧',orbit:'环绕护体',turret:'自动炮台',mine:'延时陷阱'};
  const timeText=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
  D.TAGS=TAGS;D.WEAPON_TYPES=TYPES;D.formatTime=timeText;
  class UI{
    constructor(game){this.g=game;this.home=document.getElementById('viewHome');this.play=document.getElementById('viewPlay');this.overlay=document.getElementById('overlay');this.modal=document.getElementById('modal');this.selectedCharacter='geo';this.weaponKey='';this.mapKey='';this.bannerTimer=null;this.toastTimers=new Set();this.panel='';this.lastFocus=null;
      this.clickHandler=e=>{const btn=e.target.closest('[data-action]');if(btn&&!btn.disabled){e.preventDefault();this.g.sound.unlock?.();this.handle(btn.dataset.action,btn.dataset);}else if(e.target===this.overlay)this.dismiss();};
      this.changeHandler=e=>{if(e.target.id==='importSaveFile'){this.importSave(e.target.files?.[0]);return;}if(e.target.id==='difficulty')document.getElementById('difficultyDesc').textContent=D.DIFFICULTIES[e.target.value].description;const setting=e.target.dataset.setting;if(setting){this.g.setSetting(setting,e.target.type==='checkbox'?e.target.checked:e.target.value);this.g.sound.configure?.(this.g.meta.settings);}if(['catalogSearch','catalogTag','catalogRarity'].includes(e.target.id))this.filterCatalog();};
      document.addEventListener('click',this.clickHandler);document.addEventListener('input',this.changeHandler);
    }
    heading(title,kicker='',subtitle='',close=true){return `<div class="modal-heading"><div>${kicker?`<div class="eyebrow">${E(kicker)}</div>`:''}<h2 id="modal-title">${E(title)}</h2>${subtitle?`<p class="modal-subtitle">${E(subtitle)}</p>`:''}</div>${close?'<button class="modal-close" data-action="back" aria-label="关闭对话框">×</button>':''}</div>`;}
    open(html,classes='',panel=''){if(this.overlay.hidden)this.lastFocus=document.activeElement;this.g.input.fire=false;this.panel=panel;this.overlay.hidden=false;this.modal.className=`modal ${classes}`;this.modal.innerHTML=html;this.modal.scrollTop=0;this.overlay.setAttribute('aria-labelledby','modal-title');Promise.resolve().then(()=>{const first=this.modal.querySelector('button:not(:disabled),input,select');(first||this.modal).focus({preventScroll:true});});}
    close(){this.overlay.hidden=true;this.modal.innerHTML='';this.panel='';this.g.input.fire=false;if(this.lastFocus&&document.contains(this.lastFocus))this.lastFocus.focus({preventScroll:true});this.lastFocus=null;}
    dismiss(){if(['choice','story','bossIntro','winning','victory','dead'].includes(this.g.mode))return;if(this.g.mode==='menu'){this.close();return;}this.g.closePanel();}
    menu(){this.home.hidden=false;this.play.hidden=true;document.body.classList.remove('in-game');this.close();this.renderCharacters();document.getElementById('continueBtn').hidden=!this.g.hasSave();document.getElementById('graduateChoice').hidden=this.g.meta.wins<=0;document.getElementById('bestLabel').textContent=this.g.meta.runs?`最佳 ${this.g.meta.best.toLocaleString('zh-CN')} 分 · 醒来 ${this.g.meta.wins} 次`:'你的冒险，从第一节水课开始。';
      if(!this.g.storage.available)this.toast('浏览器限制了本地存储。可以游玩，但关闭页面后可能无法保留进度。',7000);
    }
    showPlay(){this.home.hidden=true;this.play.hidden=false;document.body.classList.add('in-game');this.weaponKey='';this.mapKey='';}
    renderCharacters(){document.getElementById('characterCards').innerHTML=D.CHARACTERS.map(c=>`<button class="character-card ${c.id===this.selectedCharacter?'selected':''}" data-action="character" data-id="${c.id}" aria-pressed="${c.id===this.selectedCharacter}"><span class="avatar">${D.iconSvg(c.id==='geo'?'helmet':c.id==='early'?'clock':'pen',c.color,49)}</span><span><h3>${c.name}</h3><p>${c.subtitle}</p><small>${c.passive}</small></span></button>`).join('');}
    readStart(){return{character:this.selectedCharacter,difficulty:document.getElementById('difficulty').value,seed:document.getElementById('seed').value,graduate:document.getElementById('graduate').checked};}
    start(){this.pendingStart=this.readStart();if(this.g.hasSave()){this.open(this.heading('重新入梦？','NEW DREAM','上次的房间检查点仍在。开始新梦境会替换它。',false)+`<div class="modal-actions"><button class="button secondary" data-action="load">继续上次</button><button class="button primary" data-action="confirmStart">开始新的梦境</button><button class="button ghost" data-action="cancelStart">返回</button></div>`,'narrow','confirm');}else this.begin(this.pendingStart);}
    begin(options){this.showPlay();this.close();this.g.start(options);this.update();}
    handle(action,data){
      switch(action){
        case 'character':this.selectedCharacter=data.id;this.renderCharacters();break;
        case 'start':this.start();break;
        case 'confirmStart':this.begin(this.pendingStart);break;
        case 'cancelStart':this.close();break;
        case 'load':this.showPlay();if(!this.g.load())this.menu();break;
        case 'back':this.dismiss();break;
        case 'pause':this.g.pause();break;
        case 'resume':this.g.resume();break;
        case 'map':this.g.pause('map');break;
        case 'inventory':if(this.g.mode==='playing')this.g.pause('inventory');else{this.g.mode='inventory';this.inventory();}break;
        case 'selectWeapon':if(this.g.mode==='playing')this.g.swap(Number(data.slot));break;
        case 'guide':this.help();break;
        case 'settings':if(this.g.mode==='playing')this.g.mode='paused';this.settings();break;
        case 'catalog':this.catalog();break;
        case 'meta':this.meta();break;
        case 'buyMeta':if(!this.g.buyMeta(data.id))this.toast('灵感不足，或该项已达到三级上限。');this.meta();break;
        case 'storyNext':this.nextStory();break;
        case 'skipStory':this.finishStory();break;
        case 'bossBegin':this.bossCallback?.();break;
        case 'relic':this.g.chooseReward(data.id);break;
        case 'replace':this.g.chooseReward(Number(data.slot));break;
        case 'salvage':this.g.chooseReward('salvage');break;
        case 'buy':this.g.buy(Number(data.index));break;
        case 'upgrade':this.g.upgrade(Number(data.slot));break;
        case 'eventChoice':this.g.chooseEvent(Number(data.index));break;
        case 'quit':this.open(this.heading('先到这里，下次再醒。','RETURN TO MENU','回到菜单后，将从最近的房间检查点继续；未清完的战斗会重新开始。',false)+`<div class="modal-actions"><button class="button secondary" data-action="resume">继续战斗</button><button class="button primary" data-action="quitConfirm">返回主菜单</button></div>`,'narrow','quit');break;
        case 'quitConfirm':this.g.returnToMenu();break;
        case 'home':this.g.returnToMenu();break;
        case 'retry':{const r=this.g.run;this.begin({character:r.character,difficulty:r.difficulty,seed:r.seed,skipStory:true});break;}
        case 'newDream':{const r=this.g.run;this.begin({character:r.character,difficulty:r.difficulty,skipStory:true});break;}
        case 'results':this.results(true);break;
        case 'certificate':this.certificate();break;
        case 'copySeed':this.copySeed();break;
        case 'exportSave':this.exportSave();break;case 'importSave':document.getElementById('importSaveFile')?.click();break;
      }
    }
    update(){
      const g=this.g;if(!g.run)return;const p=g.player,s=g.stats;
      for(const [id,v,max]of[['hp',p.hp,s.maxHp],['shield',p.shield,s.maxShield],['energy',p.energy,s.maxEnergy]]){document.getElementById(id+'Text').textContent=`${Math.ceil(Math.max(0,v))} / ${Math.round(max)}`;document.getElementById(id+'Fill').style.width=`${D.clamp(v/max*100,0,100)}%`;}
      document.getElementById('chapterLabel').textContent=`${D.FLOORS[g.run.floor].short} · ${String(g.run.floor+1).padStart(2,'0')}`;
      document.getElementById('roomLabel').textContent=`${D.ROOM_TYPES[g.room.type][0]} ${String(g.run.roomId+1).padStart(2,'0')}${g.room.cleared?' · 已开放':` · ${g.enemies.length} 敌人`}`;
      document.getElementById('coinsLabel').textContent=g.run.coins;
      document.getElementById('goalLabel').textContent=g.room.cleared?(g.room.loot?'战利品在地上 · 靠近按 E 拾取':g.portal?'靠近中央传送阵，按 E 前往下一章':'出口开放 · 探索地图，寻找本层首领'):'房门已锁 · 清理所有敌人';
      document.getElementById('timeLabel').textContent=`${timeText(g.run.elapsed)} · 种子 ${g.run.seed}`;
      const syn=D.activeSynergies(g.run.inventory);document.getElementById('synergyLabel').textContent=syn.length?syn.map(x=>x.name).join(' / '):'不同标签，碰撞出新的搭配';
      for(const [id,cd,label]of[['dashStatus',p.dashCd,'空格 · 闪避'],['skillStatus',p.skillCd,'Q · 拒绝内卷'],['drinkStatus',p.drinkCd,'R · 喝水']]){const el=document.getElementById(id);el.textContent=cd>0?`${label} ${cd.toFixed(1)}s`:label;el.classList.toggle('cooling',cd>0);}
      const weaponKey=g.run.inventory.map(w=>`${w.id}:${w.level}`).join(',')+'/'+g.run.selected;
      if(weaponKey!==this.weaponKey){this.weaponKey=weaponKey;document.getElementById('weaponSlots').innerHTML=g.run.inventory.map((held,i)=>{const w=D.WEAPONS[held.id],rare=D.RARITIES[w.rarity];return `<button class="weapon-slot ${g.run.selected===i?'active':''}" style="--rarity:${rare.color}" data-action="selectWeapon" data-slot="${i}" aria-pressed="${g.run.selected===i}"><span class="weapon-icon">${D.iconSvg(w.icon,rare.color,40)}</span><span><h4><span class="slot-key">${i+1}</span>${E(w.name)}${held.level?` +${held.level}`:''}</h4><p>${rare.name} · ${TYPES[w.type]||w.type} · ${w.energy?'专注 '+w.energy:'零耗能'}</p></span></button>`;}).join('');}
      const mapKey=`${g.run.floor}/${g.run.roomId}/${g.run.floors[g.run.floor].rooms.map(r=>Number(r.visited)+':'+Number(r.cleared)).join()}`;
      if(mapKey!==this.mapKey){this.mapKey=mapKey;document.getElementById('miniMap').innerHTML=D.mapSVG(g);}
    }
    toast(text,duration=3300){const parent=document.getElementById('toasts'),el=document.createElement('div');el.className='toast';el.textContent=text;parent.appendChild(el);while(parent.children.length>3)parent.firstChild.remove();const timer=setTimeout(()=>{el.classList.add('out');const t=setTimeout(()=>{el.remove();this.toastTimers.delete(t);},320);this.toastTimers.add(t);this.toastTimers.delete(timer);},duration);this.toastTimers.add(timer);}
    banner(title,subtitle){const el=document.getElementById('banner');if(this.bannerTimer)clearTimeout(this.bannerTimer);el.innerHTML=`<strong>${E(title)}</strong><small>${E(subtitle||'')}</small>`;el.hidden=false;this.bannerTimer=setTimeout(()=>{el.hidden=true;this.bannerTimer=null;},3300);}
    story(pages,callback){this.storyPages=pages;this.storyIndex=0;this.storyCallback=callback;this.storyEnding=false;this.renderStory();}
    renderStory(){const p=this.storyPages[this.storyIndex],icon=['clock','slides','book','hammer'][this.storyIndex%4];this.open(this.heading(p.speaker,this.storyEnding?'BACK TO REALITY':'PROLOGUE / 课间梦境','',false)+`<div class="story-layout"><div class="story-art">${D.iconSvg(this.storyEnding?'diploma':icon,'#adc79b',125)}</div><div><p class="story-text">${E(p.text)}</p><div class="story-progress">${this.storyPages.map((_,i)=>`<i class="${i<=this.storyIndex?'active':''}"></i>`).join('')}</div></div></div><div class="modal-actions"><button class="button ghost" data-action="skipStory">${this.storyEnding?'查看奖励':'跳过序章'}</button><button class="button primary" data-action="storyNext">${this.storyIndex===this.storyPages.length-1?(this.storyEnding?'下课了':'醒进梦里'):'下一页'} →</button></div>`,this.storyEnding?'ending':'','story');}
    nextStory(){if(this.storyIndex<this.storyPages.length-1){this.storyIndex++;this.renderStory();}else this.finishStory();}
    finishStory(){const fn=this.storyCallback;this.storyCallback=null;this.close();fn?.();}
    bossIntro(floor,callback){this.bossCallback=callback;this.open(this.heading('迟到的挑战','BOSS ENCOUNTER','',false)+`<div class="boss-intro"><div class="boss-emblem">${D.iconSvg(floor.boss==='ta'?'laser':floor.boss==='chef'?'ladle':'diploma','#d5ba8e',104)}</div><div><div class="eyebrow">${E(floor.short)} · 守关者</div><h2>${E(floor.bossName)}</h2><blockquote>${E(floor.bossQuote)}</blockquote><p>先看红色预警，再躲攻击。环形弹幕有缺口，闪避和「拒绝内卷」都能帮助你。</p></div></div><div class="modal-actions"><button class="button primary" data-action="bossBegin">开始答辩 ↗</button></div>`,'dark','bossIntro');}
    choice(pending){
      if(pending.type==='relic')this.open(this.heading('带走一份灵感','CHOOSE A RELIC',`${pending.source} · 三选一（候选不足时按剩余数量展示）` ,false)+`<div class="reward-grid">${pending.options.map(id=>{const r=D.RELICS.find(r=>r.id===id);return `<button class="reward-card" data-action="relic" data-id="${r.id}"><span class="reward-icon">${D.iconSvg(r.icon,'#b4d197',75)}</span><span class="relic-count">本局唯一遗物</span><h3>${E(r.name)}</h3><p>${E(r.description)}</p><span class="pick-label">选择这一份 →</span></button>`;}).join('')}</div><p class="minor-text">已获得的遗物不会重复出现。暂停背包中可查看所有效果。</p>`,'','choice');
      else{
        const held=pending.weapon,w=D.WEAPONS[held.id],rare=D.RARITIES[w.rarity];
        this.open(this.heading('找到一件好东西','WEAPON FOUND',pending.source,false)+`<div class="weapon-offer"><div class="big-icon">${D.iconSvg(w.icon,rare.color,92)}</div><div><span class="rarity-badge" style="--rarity:${rare.color}">${rare.name} · ${TAGS[w.tag]}</span><h3>${E(w.name)}${held.level?' +'+held.level:''}</h3><p>${E(w.description)}</p><div class="weapon-stats"><span>机制 ${TYPES[w.type]}</span><span>单次基础 ${Math.round(w.damage*rare.scale)}</span><span>间隔 ${w.interval.toFixed(2)}s</span><span>专注 ${w.energy}</span></div></div></div><div class="replace-grid">${this.g.run.inventory.map((old,i)=>{const ow=D.WEAPONS[old.id];const next=this.g.run.inventory.map((v,j)=>j===i?held:v);const syn=D.activeSynergies(next);return `<button class="replace-card" data-action="replace" data-slot="${i}"><span class="eyebrow">替换武器槽 ${i+1}</span><h4>${E(ow.name)}${old.level?' +'+old.level:''}</h4><p>${syn.length?'激活：'+syn.map(s=>E(s.name)).join(' / '):'新装备将直接替换旧装备'}</p></button>`;}).join('')}</div><div class="modal-actions"><span class="minor-text">被替换的旧武器离场，不返还币。</span><button class="button secondary" data-action="salvage">拆解新武器 · +${8+w.rarity*4} 学分币</button></div>`,'','choice');
      }
    }
    help(){
      if(this.g.mode==='playing')this.g.mode='paused';const controls=[['WASD','移动（方向键也可）'],['鼠标','瞄准；按住左键射击'],['空格','闪避，短暂无敌'],['E','拾取、对话、商店、传送'],['1 / 2','切换两把武器；滚轮也可'],['Q','拒绝内卷：清弹与范围伤害'],['R','喝水回复专注，短暂停火'],['F','开 / 关自动瞄准射击'],['M / Tab','地图 / 背包'],['Esc','暂停；切出标签页也会暂停']];
      this.open(this.heading('新生指南','HOW TO WAKE UP','目标：穿过教学楼、食堂与行政楼，击败梦境校长。')+`<div class="control-grid">${controls.map(([k,v])=>`<div class="control-item"><kbd>${k}</kbd><span>${v}</span></div>`).join('')}</div><div class="guide-copy"><p><strong>房间：</strong>清完敌人后，走向发光的门即可切换房间。商店、休息、宝箱、奇遇与精英分布在岔路。地图会提示已发现的邻接房间。</p><p><strong>专注：</strong>弹药无限，但部分武器消耗专注；专注自动恢复。备用的零耗能武器不会断火。R 可在 0.82 秒喝水后回复 48 专注。</p><p><strong>构筑：</strong>最多携带两把武器。相同或互补的标签可形成羁绊，升级最多 +3。喷水后用电系攻击潮湿目标会有额外伤害。炮台、环绕物在换武器后会继续攻击，适合作为副武器。</p><p><strong>生存：</strong>红色圆圈和线是攻击预警，不是奖励。护盾在一段时间未受伤后恢复；低血量清房有少量补给。</p><p><strong>手机：</strong>建议横屏。左摇杆移动，右摇杆瞄准射击，下方按钮执行技能。也可在设置里打开自动射击。</p><p><strong>存档：</strong>只保存房间检查点与已确认的奖励，不保存未完成战斗的逐帧现场。继续游戏可能重打当前房间；已消费与已选择的物品不会重复领取。</p></div><div class="modal-actions"><button class="button primary" data-action="back">准备好了</button></div>`,'','help');
    }
    settings(){const s=this.g.meta.settings,rows=[['music','原声伴奏','原创合成器旋律与战斗节奏。'],['aimAssist','辅助瞄准','射击时自动选择最近且可见的目标。'],['autoFire','自动射击','自动瞄准并持续攻击；桌面可按 F 切换。'],['shake','屏幕震动','开启击中、爆炸与首领阶段的震动。'],['particles','粒子效果','关闭后减少装饰粒子，不影响攻击判定。']];
      this.open(this.heading('把梦调到舒服的频率','SETTINGS','设置即时生效，并保存在此浏览器。')+`<div class="settings-row"><div><strong>总音量</strong><small>首次点击按钮后才启动音频。</small></div><input type="range" min="0" max="1" step=".05" value="${s.volume}" data-setting="volume" aria-label="总音量"></div>${rows.map(([id,title,desc])=>`<label class="settings-row"><span><strong>${title}</strong><small>${desc}</small></span><input type="checkbox" data-setting="${id}" ${s[id]?'checked':''}></label>`).join('')}<div class="status-note">${this.g.storage.available?'本地存储可用。无账号、无广告、无外部素材请求。':'此环境的本地存储不可用，进度可能仅保留在本次页面中。'}<br>本地得分不是防作弊的联网排行榜。</div><div class="modal-actions"><button class="button ghost" data-action="exportSave">导出存档备份</button>${this.g.mode==='menu'?'<button class="button ghost" data-action="importSave">导入备份</button><input id="importSaveFile" type="file" accept="application/json,.json" hidden>':''}<button class="button primary" data-action="back">完成</button></div>`,'narrow','settings');
    }
    pause(){const r=this.g.run;this.open(this.heading('先喘口气','TAKE A BREAK',D.TIPS[Math.floor(this.g.clock)%D.TIPS.length])+`<div class="pause-stats"><div class="pause-stat"><b>${timeText(r.elapsed)}</b><span>本局用时</span></div><div class="pause-stat"><b>${r.kills}</b><span>击败怪物</span></div><div class="pause-stat"><b>${r.clears}</b><span>清理房间</span></div><div class="pause-stat"><b>${r.coins}</b><span>学分币</span></div></div><div class="pause-menu"><button class="button primary" data-action="resume">继续梦境</button><button class="button secondary" data-action="inventory">本局背包</button><button class="button secondary" data-action="settings">设置</button><button class="button secondary" data-action="guide">新生指南</button></div><div class="status-note">存档以房间为检查点。当前种子：<strong>${E(r.seed)}</strong> · ${D.DIFFICULTIES[r.difficulty].name}</div><div class="modal-actions"><button class="button ghost" data-action="copySeed">复制种子</button><button class="button ghost" data-action="quit">返回主菜单</button></div>`,'narrow','pause');}
    inventory(){const r=this.g.run,syn=D.activeSynergies(r.inventory),s=this.g.stats;
      this.open(this.heading('这一局，靠这些醒来','BACKPACK',`全伤害 +${Math.round(s.damage*100)}% · 暴击 ${Math.round(s.crit*100)}% · 专注恢复 ${s.energyRegen.toFixed(0)}/秒`)+`<div class="replace-grid">${r.inventory.map((held,i)=>{const w=D.WEAPONS[held.id],rare=D.RARITIES[w.rarity];return `<div class="replace-card"><span class="eyebrow">SLOT 0${i+1} · ${rare.name} · ${TAGS[w.tag]}</span><div class="catalog-card-top">${D.iconSvg(w.icon,rare.color,53)}<h4>${E(w.name)}${held.level?' +'+held.level:''}</h4></div><p>${E(w.description)}</p></div>`;}).join('')}</div><h3 class="section-label">已激活羁绊 / ${syn.length}</h3><div class="synergy-list">${syn.length?syn.map(s=>`<div class="synergy-card"><h4>${s.name}</h4><p>${s.description}</p></div>`).join(''):'<p>当前没有羁绊。替换武器时会预告新组合效果。</p>'}</div><h3 class="section-label">遗物 / ${r.relics.length}</h3><div class="relic-grid">${r.relics.map(id=>{const relic=D.RELICS.find(v=>v.id===id);return `<div class="relic-item">${D.iconSvg(relic.icon,'#b5cba1',39)}<div><strong>${relic.name}</strong><small>${relic.description}${id==='secondChance'&&r.usedRevive?'（本局已使用）':''}</small></div></div>`;}).join('')||'<p>清房、精英挑战与校园奇遇都可能带来遗物。</p>'}</div><div class="modal-actions"><button class="button primary" data-action="back">继续冒险</button></div>`,'wide','inventory');
    }
    map(){this.open(this.heading(D.FLOORS[this.g.run.floor].name,'FLOOR MAP','亮色实心圆是你。未知区域以 ? 标记，清过的房间不会再次刷怪。')+`<div class="map-body">${D.mapSVG(this.g,true)}</div><div class="map-legend">${Object.entries(D.ROOM_TYPES).map(([k,[label,symbol]])=>`<span><b>${symbol}</b>${label}</span>`).join('')}</div><p>主路通向首领；岔路可以取得宝箱、休息、交易、奇遇或挑战精英。返回战场后，走到相应方向的门即可移动。</p><div class="modal-actions"><button class="button primary" data-action="back">返回战场</button></div>`,'dark wide','map');}
    shop(){const g=this.g,items=g.getShop();this.open(this.heading('学长的毕业甩卖','CAMPUS MARKET',`余额 ${g.run.coins} 学分币 · 本层交易不接受花呗，也不接受画饼。`)+`<div class="shop-grid">${items.map(item=>{const w=item.type==='weapon'?D.WEAPONS[item.id]:null,name=w?w.name:item.type==='heal'?'热乎乎的夜宵':'神秘遗物盲盒',icon=w?w.icon:item.type==='heal'?'meal':'parcel',desc=w?D.RARITIES[w.rarity].name+' · '+TYPES[w.type]:item.type==='heal'?'回复 35 生命':'三件未拥有遗物中选一';return `<div class="shop-card ${item.sold?'sold':''}">${D.iconSvg(icon,w?D.RARITIES[w.rarity].color:'#bdd19f',61)}<h3>${E(name)}</h3><p>${desc}</p><button class="button ${item.sold?'ghost':'secondary'} small" data-action="buy" data-index="${item.index}" ${item.sold?'disabled':''}>${item.sold?'已经售出':item.price+' 学分币'}</button></div>`;}).join('')}</div><h3 class="section-label">学长的维修台 · 每级 +14% 基础伤害，最多 +3</h3><div class="upgrade-row">${g.run.inventory.map((held,i)=>{const w=D.WEAPONS[held.id];return `<div class="upgrade-card">${D.iconSvg(w.icon,D.RARITIES[w.rarity].color,41)}<div><h4>${E(w.name)} +${held.level}</h4><p>${held.level>=3?'已达到上限':'升级不改变武器机制与耗能'}</p></div><button class="button secondary small" data-action="upgrade" data-slot="${i}" ${held.level>=3?'disabled':''}>${held.level>=3?'MAX':g.upgradePrice(i)+' 币'}</button></div>`;}).join('')}</div><div class="modal-actions"><button class="button primary" data-action="back">先逛到这里</button></div>`,'wide','shop');}
    event(event){this.open(this.heading(event.title,'A SMALL CAMPUS STORY','',false)+`<div class="story-layout"><div class="story-art">${D.iconSvg(event.id==='corebox'||event.id==='office'?'core':'letter','#b7c991',110)}</div><p class="story-text">${E(event.text)}</p></div><div class="event-options">${event.choices.map((c,i)=>`<button class="event-option" data-action="eventChoice" data-index="${i}"><strong>${E(c.text)} →</strong><small>${E(c.detail)}</small></button>`).join('')}</div><div class="modal-actions"><button class="button ghost" data-action="back">先想一想</button></div>`,'','event');}
    catalog(){this.open(this.heading('校园武器图鉴','48 WAYS TO SURVIVE',`已发现 ${this.g.meta.discovered.length} / ${Object.keys(D.WEAPONS).length} 件。所有机制都可以在这里查阅。`)+`<div class="catalog-toolbar"><input id="catalogSearch" type="search" placeholder="搜索武器、描述或攻击方式" aria-label="搜索武器"><select id="catalogTag" aria-label="按武器标签筛选"><option value="">所有标签</option>${Object.entries(TAGS).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select><select id="catalogRarity" aria-label="按品质筛选"><option value="">所有品质</option>${D.RARITIES.map((r,i)=>`<option value="${i}">${r.name}</option>`).join('')}</select></div><div class="catalog-grid" id="catalogGrid"></div><div class="modal-actions"><button class="button primary" data-action="back">合上图鉴</button></div>`,'wide','catalog');this.filterCatalog();}
    filterCatalog(){const grid=document.getElementById('catalogGrid');if(!grid)return;const search=document.getElementById('catalogSearch').value.toLowerCase().trim(),tag=document.getElementById('catalogTag').value,rarity=document.getElementById('catalogRarity').value;const weapons=Object.values(D.WEAPONS).filter(w=>(!tag||w.tag===tag)&&(rarity===''||w.rarity===Number(rarity))&&(!search||`${w.name} ${w.description} ${TYPES[w.type]} ${TAGS[w.tag]}`.toLowerCase().includes(search)));
      grid.innerHTML=weapons.map(w=>{const rare=D.RARITIES[w.rarity],owned=this.g.meta.discovered.includes(w.id);return `<article class="catalog-card"><div class="catalog-card-top">${D.iconSvg(w.icon,rare.color,49)}<div><h3>${E(w.name)}</h3><span class="tag-label">${rare.name} · ${TAGS[w.tag]}</span></div></div><p>${E(w.description)}</p><small>${TYPES[w.type]} · 基础 ${Math.round(w.damage*rare.scale)} · 间隔 ${w.interval.toFixed(2)}s · 专注 ${w.energy}</small><p class="undiscovered">${w.unlock&&this.g.meta.wins===0?'通关后解锁':owned?'✓ 已在梦境中发现':'尚未在梦境中发现'}</p></article>`;}).join('')||'<p>没有找到匹配的武器。</p>';
    }
    meta(){const m=this.g.meta,upgrades=[['health','体能训练','每级最大生命 +5','heart'],['focus','专注练习','每级专注恢复 +1/秒','battery'],['shield','心理缓冲','每级最大护盾 +3','headset']];this.open(this.heading('梦醒之后，也有成长','AFTER THE DREAM',`灵感余额 ${m.inspiration} · 所有成长最多三级，不会无限叠加碾压数值。`)+`<div class="meta-grid">${upgrades.map(([id,name,desc,icon])=>{const lvl=m.upgrades[id]||0,price=18+lvl*16;return `<div class="meta-card">${D.iconSvg(icon,'#aec999',59)}<h3>${name}</h3><div class="upgrade-pips">${[0,1,2].map(i=>`<i class="${i<lvl?'on':''}"></i>`).join('')}</div><p>${desc}<br>从下一场新梦境生效</p><button class="button secondary small" data-action="buyMeta" data-id="${id}" ${lvl>=3?'disabled':''}>${lvl>=3?'已满级':price+' 灵感'}</button></div>`;}).join('')}</div><div class="pause-stats"><div class="pause-stat"><b>${m.runs}</b><span>已结束的梦</span></div><div class="pause-stat"><b>${m.wins}</b><span>成功醒来</span></div><div class="pause-stat"><b>${m.best}</b><span>本地最高分</span></div><div class="pause-stat"><b>${m.discovered.length}/48</b><span>武器图鉴</span></div></div><h3 class="section-label">最近梦境记录</h3>${m.history.map(r=>`<div class="history-line"><strong>${r.won?'成功醒来':'梦境未完'} · ${r.score} 分</strong><span>${D.DIFFICULTIES[r.difficulty]?.name||'正常修读'} · ${timeText(r.elapsed)}</span><span>${E(r.seed)}</span></div>`).join('')||'<p>还没有结束的冒险。无论成功或失败，都能带回一点灵感。</p>'}<div class="status-note">${m.wins?'已解锁「毕业证发射器」。主菜单可选择把它带入下一场梦，也会加入后续随机掉落。':'首次通关奖励：毕业证发射器、专属毕业纪念证书，以及额外灵感。'}<br>记录仅保存在当前浏览器，不上传到服务器。</div><div class="modal-actions"><button class="button primary" data-action="back">回到早八</button></div>`,'wide','meta');}
    victory(){this.storyPages=[{speaker:'下课铃 · 现实世界',text:'你在一阵掌声里抬起头。\n课本没有漏水，手机也没有发射导弹。窗外的云，终于动了。'},{speaker:'老师',text:'“这节课就到这里。”\n\n你翻开笔记本，最后一页不知什么时候多了一行字：\n「无需把生活每一刻，都活成一场考试。」'},{speaker:'你的口袋',text:'里面躺着一张小小的毕业证。\n不是说你已经毕业了，而是你终于学会：\n在最荒诞的日子里，也给自己留一点醒来的勇气。'}];this.storyIndex=0;this.storyCallback=()=>this.results(true);this.storyEnding=true;this.renderStory();}
    gameOver(){this.results(false);}
    results(won){const r=this.g.run,confetti=won?`<div class="confetti-field" aria-hidden="true">${Array.from({length:38},(_,i)=>`<i style="left:${(i*37)%100}%;background:${['#8eb786','#dec080','#ce9a8c','#a8c9af'][i%4]};animation-delay:${-(i%11)*.37}s;animation-duration:${3.4+(i%5)*.7}s;transform:rotate(${i*31}deg)"></i>`).join('')}</div>`:'';
      this.open(`${confetti}<div class="results-top"><div class="eyebrow">${won?'YOU MADE IT BACK':'EVERY DREAM LEAVES SOMETHING'}</div>${D.iconSvg(won?'diploma':'clock',won?'#d6bd81':'#b8c597',90)}<h2 id="modal-title">${won?'下课了。':'这次，先睡到这里。'}</h2><p>${won?'梦境校长已击败。最后一个学分，是留给自己的。':'没有白走的房间。带上经验和灵感，下一次会更接近铃声。'}</p></div><div class="pause-stats"><div class="pause-stat"><b>${r.score}</b><span>本局成绩</span></div><div class="pause-stat"><b>${timeText(r.elapsed)}</b><span>冒险用时</span></div><div class="pause-stat"><b>${r.kills}</b><span>击败怪物</span></div><div class="pause-stat"><b>+${r.inspiration}</b><span>带回的灵感</span></div></div>${won?`<div class="result-rewards">${D.iconSvg('diploma','#d8bc86',65)}<div><h3>毕业证发射器 · 已解锁</h3><p>以后开局可以携带，也会加入后续随机掉落。你的毕业纪念证书已经准备好。<br>${this.g.storage.available?'完整奖励已写入当前浏览器存档。':'当前浏览器限制存储，奖励仅在本次页面中保留；建议立即导出备份。'}</p></div></div>`:`<div class="status-note">${D.TIPS[(r.kills+r.clears)%D.TIPS.length]}<br>难度：${D.DIFFICULTIES[r.difficulty].name} · 已到达第 ${r.floor+1} 章 · 种子 ${E(r.seed)}</div>`}<div class="modal-actions">${won?'<button class="button secondary" data-action="certificate">保存毕业纪念证书</button>':'<button class="button secondary" data-action="retry">重试同一种子</button>'}<button class="button secondary" data-action="home">回到主菜单</button><button class="button primary" data-action="newDream">再做一场不同的梦 ↗</button></div>`,won?'ending':'','results');
    }
    download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
    certificate(){const r=this.g.run;if(!r?.won)return;const date=new Date().toISOString().slice(0,10);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="840" viewBox="0 0 1200 840"><rect width="1200" height="840" fill="#f6efdc"/><rect x="35" y="35" width="1130" height="770" rx="15" fill="none" stroke="#6f8b62" stroke-width="3"/><rect x="53" y="53" width="1094" height="734" rx="10" fill="none" stroke="#c1b989"/><g font-family="system-ui,'Microsoft YaHei',sans-serif" text-anchor="middle" fill="#385239"><text x="600" y="130" font-size="18" letter-spacing="7">DREAM CAMPUS · 梦醒纪念</text><text x="600" y="264" font-size="76" font-weight="800">这一次，你醒来了。</text><text x="600" y="340" font-size="25">${E(D.CHARACTERS.find(c=>c.id===r.character).name)}，已找回最后一个学分。</text><text x="600" y="425" font-size="23">穿过教学楼、食堂与行政楼 · 击败梦境校长</text><text x="600" y="489" font-size="22">成绩 ${r.score} 分  /  用时 ${timeText(r.elapsed)}  /  击败 ${r.kills} 只怪物</text><text x="600" y="554" font-size="18">梦境种子：${E(r.seed)} · ${D.DIFFICULTIES[r.difficulty].name}</text><text x="600" y="654" font-size="25" fill="#799161">“无需把生活每一刻，都活成一场考试。”</text><text x="600" y="727" font-size="15">${date} · 仅为游戏通关纪念，不代表真实学位或学历</text></g><path d="m1038 103 13 31 33 2-25 23 8 33-29-18-28 18 8-33-26-23 34-2Z" fill="#cbb57c"/></svg>`;this.download('水课梦魇-毕业纪念证书.svg',svg,'image/svg+xml;charset=utf-8');}
    async importSave(file){
      if(!file)return;if(this.g.mode!=='menu'){this.toast('请先返回主菜单再导入。');return;}
      if(file.size>1000000){this.toast('存档文件过大，最多接受 1 MB。');return;}
      try{const data=JSON.parse(await file.text());if(!window.confirm('导入将替换当前浏览器的游戏记录和房间检查点。建议先导出备份。继续吗？'))return;window.DreamCampus.importSave(data);this.toast('备份已导入，可以继续上次的梦。');}
      catch(e){this.toast('导入失败，原记录未替换：'+e.message,6000);}
    }
    async copySeed(){const seed=this.g.run?.seed||'';try{await navigator.clipboard.writeText(seed);this.toast('梦境种子已复制：'+seed);}catch(e){this.toast('本次梦境种子：'+seed,6000);}}
    exportSave(){const payload={schema:1,game:'dream-campus',exportedAt:new Date().toISOString(),meta:this.g.meta,checkpoint:this.g.storage.read('run',null)};this.download('dream-campus-save.json',JSON.stringify(payload,null,2),'application/json');this.toast('已导出本地存档备份。');}
    destroy(){document.removeEventListener('click',this.clickHandler);document.removeEventListener('input',this.changeHandler);if(this.bannerTimer)clearTimeout(this.bannerTimer);for(const t of this.toastTimers)clearTimeout(t);this.close();}
  }
  D.UI=UI;
})(typeof window!=='undefined'?window:globalThis);
